export const BROKER_REPOSITORY = 'BROKER_REPOSITORY';
export const USER_REPOSITORY = 'USER_REPOSITORY';
export const APPOINTMENT_REPOSITORY = 'APPOINTMENT_REPOSITORY';
export const CLIENT_REPOSITORY = 'CLIENT_REPOSITORY';
export const PROPIERTY_REPOSITORY = 'PROPIERTY_REPOSITORY';
