export const AUTH_USER_LOGIN = 'AUTH_USER_LOGIN';
export const AUTH_USER_SIGNIN = 'AUTH_SIGNIN';
export const AUTH_BROKER_LOGIN = 'AUTH_BROKER_LOGIN';
export const AUTH_BROKER_SIGNIN = 'AUTH_BROKER_SIGNIN';
export const AUTH_ADMIN_LOGIN = 'AUTH_ADMIN_LOGIN';
export const CLEAR_CREATED_BROKER = 'CLEAR_CREATED_BROKER';
export const GET_BROKERS = 'GET_BROKERS';
