export const AUTH_USER_LOGIN = 'AUTH_USER_LOGIN';
export const AUTH_USER_SIGNIN = 'AUTH_SIGNIN';
export const AUTH_BROKER_LOGIN = 'AUTH_BROKER_LOGIN';
export const AUTH_BROKER_SIGNIN = 'AUTH_BROKER_SIGNIN';
