version: '4.12'

services:
  database: 
    image: postgres:13
    container_name: appropiatedb
    environment: 
      - POSTGRES_USER=nacho
      - POSTGRES_PASSWORD=nacho
      - POSTGRES_DB=my_db

    ports: 
      - 5433:5432
    volumes: 
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data: {}